<?php
$z[0]=Array("arcurl","",140,155);
$z[0][4]=array();
$z[1]=Array("pubdate","",287,334);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y-m-d',@me)";
$z[2]=Array("title","",379,393);
$z[2][4]=array();
$z[3]=Array("shorttitle","",446,465);
$z[3][4]=array();
$z[4]=Array("description","",569,619);
$z[4][4]=array();
$z[4][4]['function']="cn_substr(@me,140)";
$z[5]=Array("picname","",749,765);
$z[5][4]=array();

?>