<div id="newsitem_0" class="wow newstitem left" style="visibility: visible;">
                <a class="newscontent" target="_blank" href="[field:arcurl/]">
                  <div class="news_wrapper">
                    <div class="newsbody">
                      <p class="date">[field:pubdate function="MyDate('Y-m-d',@me)"/]</p>
                      <p class="title">[field:title/]</p>
                      <p class="subtitle hide">[field:shorttitle/]</p>
                      <div class="separator"></div>
                      <p class="description">[field:description function="cn_substr(@me,140)"/]...</p>
                    </div>
                  </div>
                  <div class="newsimg" style="background-image:url([field:picname/])"></div>
                </a>
              </div>