<?php
$z[0]=Array("arcurl","",112,127);
$z[0][4]=array();
$z[1]=Array("pubdate","",283,326);
$z[1][4]=array();
$z[1][4]['function']="MyDate('y',@me)";
$z[2]=Array("pubdate","",366,411);
$z[2][4]=array();
$z[2][4]['function']="MyDate('m-d',@me)";
$z[3]=Array("title","",493,507);
$z[3][4]=array();
$z[4]=Array("picname","",796,812);
$z[4][4]=array();
$z[5]=Array("arcurl","",893,908);
$z[5][4]=array();

?>