
<field:cpmc itemname="产品名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:cpmc>

<field:dgsl itemname="订购数量" autofield="1" type="int" isnull="true" default=""  maxlength="250" page="">
</field:dgsl>

<field:ndxm itemname="您的姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ndxm>

<field:lxdh itemname="联系电话" autofield="1" type="int" isnull="true" default=""  maxlength="250" page="">
</field:lxdh>

<field:txdz itemname="通信地址" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:txdz>

<field:dzyx itemname="电子邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dzyx>

<field:ndyq itemname="您的要求" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:ndyq>
