<li id="projectitem_0" class="projectitem wow">
                    <a href="[field:arcurl/]" class="projectitem_content"
                      target="_blank">
                      <div class="projectitem_wrapper">
                        <div class="project_img"><img src="[field:picname/]"
                            alt="[field:title/]" width="650" height="385" /></div>
                        <div class="project_info">
                          <div>
                            <p class="title">[field:title/]</p>
                            <p class="subtitle">[field:shorttitle/]</p>
                            <p class="description hide">
                                [field:description function="cn_substr(@me,100)"/]...
                            </p>
                          </div>
                        </div>
                      </div>
                    </a>
                  </li>