<li id="newsitem_0" class="wow newstitem left"><a class="newscontent" target="_blank"
                    href="[field:arcurl/]">
                    <div class="news_wrapper">
                      <div class="newsbody">
                        <p class="date wow"><span class="md">[field:pubdate function="MyDate('y',@me)"/]<span>-</span></span><span class="year">[field:pubdate function="MyDate('m-d',@me)"/]</span>
                        </p>
                        <p class="title wow">[field:title/]...</p>
                        <div class="separator"></div>
                        <p class="description wow">[field:description function="cn_substr(@me,140)"/]</p>
                      </div>
                    </div>
                    <div class="newsimg"
                      style="background-image:url([field:picname/])">
                    </div>
                  </a>
                  <a href="[field:arcurl/]" target="_blank" class="details">more<i
                      class="fa fa-angle-right"></i></a>
                </li>