<li class="navitem"><a class="nav-a " href="{dede:field name='typeurl'/}" target=""><span data-title="{dede:field name='typename'/}">{dede:field name='typename'/}</span><i
              class="fa fa-angle-down"></i></a>
          
          <ul class="subnav">

            {dede:channel type='son' noself='yes' }
            <li><a href="//mo004_4100.mo4.line1.uemo.net/page/72684/" target="_self"><span
                  data-title="了解我们">了解我们</span><i class="fa fa-angle-right"></i></a></li>
            {/dede:channel}
          </ul>
        </li>