<?php
$z[0]=Array("field","",44,72);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",102,131);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",133,162);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","\n            <li><a href=\"//mo004_4100.mo4.line1.uemo.net/page/72684/\" target=\"_self\"><span\n                  data-title=\"了解我们\">了解我们</span><i class=\"fa fa-angle-right\"></i></a></li>\n            ",274,538);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>