<li id="newsitem_0" class="wow newstitem left"><a class="newscontent" target="_blank"
                    href="[field:arcurl/]">
                    <div class="news_wrapper">
                      <div class="newsbody">
                        <p class="date wow"><span class="md">2016<span>-</span></span><span class="year">08-12</span>
                        </p>
                        <p class="title wow">[field:title/]</p>
                        <div class="separator"></div>
                        <p class="description wow">8月3日 广东省企业联合会 广东省企业家协会发布2016年广东省企业500强及广东省民营企业100强榜单...</p>
                      </div>
                    </div>
                    <div class="newsimg"
                      style="background-image:url({dede:global.cfg_templets_skin/}/images/150406205822.jpg)">
                    </div>
                  </a>
                  <a href="//mo004_4100.mo4.line1.uemo.net/news/post/26618/" target="_blank" class="details">more<i
                      class="fa fa-angle-right"></i></a>
                </li>