<li id="newsitem_0" class="wow newstitem left"><a class="newscontent" target="_blank"
                    href="[field:arcurl/]">
                    <div class="news_wrapper">
                      <div class="newsbody">
                        <p class="date wow"><span class="md">[field:pubdate function="MyDate('y',@me)"/]<span>-</span></span><span class="year">[field:pubdate function="MyDate('m-d',@me)"/]</span>
                        </p>
                        <p class="title wow">[field:title/]</p>
                        <div class="separator"></div>
                        <p class="description wow">{dede:field.description}...</p>
                      </div>
                    </div>
                    <div class="newsimg"
                      style="background-image:url({dede:global.cfg_templets_skin/}/images/150406205822.jpg)">
                    </div>
                  </a>
                  <a href="{dede:global.cfg_basehost/}/media_viewport/" target="_blank" class="details">more<i
                      class="fa fa-angle-right"></i></a>
                </li>