<li class="projectitem"><a href="[field:arcurl/]" target="_blank">
              <div class="project_img"><img src="[field:picname/]" width="200" height="220" /></div>
              <div class="project_info">
                <div>
                  <p class="title">[field:title/]</p>
                  <p class="subtitle">[field:shorttitle/]</p>
                  <p class="description hide">
                    [field:description function="cn_substr(@me,140)"/]
                  </p>
                </div>
              </div>
            </a>
            <a href="" target="_blank" class="details">more<i class="fa fa-angle-right"></i></a>
          </li>