<div class="projectitem">
                <a href="[field:arcurl/]" target="_blank">
                  <span class="propost_img">
                    <img src="[field:picname/]" />
                  </span>
                  <div class="project_info">
                    <div>
                      <p class="title">[field:title/]</p>
                      <p class="subtitle">[field:shorttitle/]</p>
                    </div>
                  </div>
                </a>
              </div>