<?php
$z[0]=Array("global","",75,102);
$z[0][4]=array();
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",132,164);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",285,312);
$z[2][4]=array();
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("channel","\r\n\r\n      <li class=\"navitem\">\r\n        <a class=\"nav-a \" href=\"[field:typelink/]\" target=\"_self\">\r\n          <span data-title=\"[field:typename/]\">[field:typename/]</span>\r\n        </a>\r\n      </li>\r\n\r\n      ",400,682);
$z[3][4]=array();
$z[3][4]['row']="7";
$z[3][4]['type']="top";
$z[3][4]['typeid']="1,2,3,10,11,12,4";

?>